### ISSUE TITLE
Deployment of testbed fails with "Error: No such object: manager_ara-server_1"

### ISSUE THREAD

**Issue by nerdicbynature** [osism/testbed#1052] opened 2022-02-05 10:05 UTC
Hi,

currently I am not able to deploy testbed.

Steps to reproduce:
git clone https://github.com/osism/testbed.git
cd testbed/terraform
echo "ENVIRONMENT=pluscloudopen" > local.env
make plan
make deploy
make watch

Software:
OSX 11.6.1
Terraform v1.1.5

Final error messages:
-----------------------------------------------------------------------------------------------------------------------
TASK [osism.commons.docker_compose : Install docker-compose package] ***********
changed: [testbed-manager.testbed.osism.xyz]

TASK [osism.commons.docker_compose : Copy docker-compose systemd unit file] ****
changed: [testbed-manager.testbed.osism.xyz]

RUNNING HANDLER [osism.commons.docker_compose : Reload systemd daemon] *********
ok: [testbed-manager.testbed.osism.xyz]

PLAY RECAP *********************************************************************
testbed-manager.testbed.osism.xyz : ok=47   changed=21   unreachable=0    failed=0    skipped=16   rescued=0    ignored=0

ERROR! Attempting to decrypt but no vault secrets found
cp: cannot create regular file '/opt/ansible/secrets/id_rsa.operator.pub': No such file or directory
Error: No such object: manager_ara-server_1
Error: No such object: manager_ara-server_1
Error: No such object: manager_ara-server_1
[...]
Error: No such object: manager_ara-server_1
-----------------------------------------------------------------------------------------------------------------------

Full log also available,

Kind regards,
Andre.

**Comment by osfrickler** [comment] 2022-02-07 16:41
This is a known regression caused by the introduction of TLS encryption of services. It will be fixed by https://github.com/osism/testbed/pull/1051.

**Comment by nerdicbynature** [comment] 2022-02-08 07:16
Ah... sorry, haven't noticed that.

I tried stable Branch as well. However, getting this after a couple of minutes:

-------------------------------------------------------------------------

PLAY RECAP *********************************************************************
localhost                  : ok=18   changed=5    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

Reading package lists...
Building dependency tree...
Reading state information...
python3-netifaces is already the newest version (0.10.4-1ubuntu4).
python3-netifaces set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
cp: cannot create regular file '/home/dragon/.ssh/id_rsa': No such file or directory
cp: cannot create regular file '/home/dragon/.ssh/id_rsa.pub': No such file or directory
chown: invalid user: ‘dragon:dragon’
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
sudo: unknown user: dragon
sudo: unable to initialize policy plugin
/root/manager.sh: line 30: /usr/bin/docker: No such file or directory
/root/manager.sh: line 30: /usr/bin/docker: No such file or directory
/root/manager.sh: line 30: /usr/bin/docker: No such file or directory
/root/manager.sh: line 30: /usr/bin/docker: No such file or directory
[...]
---------------------------------------------------------------------

I am wondering how I can deploy Testbed actually.

**Closed** 2022-02-08 08:02 UTC
Labels: bug
